/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_v1_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/templates": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Templates */
    get: operations["templates_api_v1_templates_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/toolbox": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Toolbox */
    get: operations["toolbox_api_v1_toolbox_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/compose": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Preview Composition */
    post: operations["preview_composition_api_v1_compose_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/projects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Projects */
    get: operations["projects_api_v1_projects_get"];
    put?: never;
    /** Create Project */
    post: operations["create_project_api_v1_projects_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/projects/{project_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Project */
    get: operations["get_project_api_v1_projects__project_id__get"];
    /** Update Project */
    put: operations["update_project_api_v1_projects__project_id__put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/projects/{project_id}/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Runs */
    get: operations["list_runs_api_v1_projects__project_id__runs_get"];
    put?: never;
    /** Execute */
    post: operations["execute_api_v1_projects__project_id__runs_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{run_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Run */
    get: operations["get_run_api_v1_runs__run_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{run_id}/tensors/{tensor_id}/values": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Tensor Values */
    get: operations["tensor_values_api_v1_runs__run_id__tensors__tensor_id__values_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Blueprint */
    Blueprint: {
      /**
       * Has Input
       * @default false
       */
      has_input: boolean;
      /** Components */
      components?: components["schemas"]["ComponentSpec"][];
    };
    /** ComponentSpec */
    ComponentSpec: {
      /** Id */
      id: string;
      /** Kind */
      kind: string;
      /** Parameters */
      parameters?: {
        [key: string]: number;
      };
    };
    /** ComponentStage */
    ComponentStage: {
      /** Id */
      id: string;
      /** Title */
      title: string;
      /** Input Shape */
      input_shape: number[];
      /** Shape */
      shape?: number[] | null;
      /** Axes */
      axes?: string[];
      /** Error */
      error?: string | null;
    };
    /** CompositionPlan */
    CompositionPlan: {
      /** Code */
      code: string;
      /** Stages */
      stages: components["schemas"]["ComponentStage"][];
      /** Valid */
      valid: boolean;
      /** Error */
      error?: string | null;
    };
    /** CompositionRequest */
    CompositionRequest: {
      blueprint: components["schemas"]["Blueprint"];
      input?: components["schemas"]["InputSpec"];
      /**
       * Capture Mode
       * @default values
       * @enum {string}
       */
      capture_mode: "values" | "shapes";
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** InputSpec */
    InputSpec: {
      /** Shape */
      shape?: number[];
      /**
       * Generator
       * @default arange
       * @enum {string}
       */
      generator: "arange" | "random" | "ones" | "zeros";
      /**
       * Dtype
       * @default float32
       * @enum {string}
       */
      dtype: "float32" | "float64" | "int64";
      /**
       * Seed
       * @default 7
       */
      seed: number;
      /** Axis Names */
      axis_names?: string[];
    };
    /** Lesson */
    Lesson: {
      /** Title */
      title: string;
      /** Summary */
      summary: string;
      /** Detail */
      detail: string;
      /**
       * Category
       * @enum {string}
       */
      category: "layout" | "compute" | "normalize" | "memory" | "generic";
      /**
       * Interaction
       * @default inspect
       * @enum {string}
       */
      interaction: "mapping" | "dot_product" | "normalization" | "inspect";
      /** Mapping */
      mapping?: number[] | null;
      /** Axis Order */
      axis_order?: number[] | null;
      /** Mapping Rule */
      mapping_rule?: ("identity" | "permutation" | "unfold") | null;
    };
    /** Operation */
    Operation: {
      /** Id */
      id: string;
      /** Index */
      index: number;
      /** Kind */
      kind: string;
      /** Function */
      function: string;
      /** Inputs */
      inputs: string[];
      /** Outputs */
      outputs: string[];
      /** Arguments */
      arguments: {
        [key: string]: unknown;
      };
      source: components["schemas"]["SourceLocation"] | null;
      /** Module */
      module: string;
      lesson: components["schemas"]["Lesson"];
      /**
       * Status
       * @default ok
       * @enum {string}
       */
      status: "ok" | "error";
      /** Error */
      error?: string | null;
    };
    /** Project */
    Project: {
      blueprint?: components["schemas"]["Blueprint"] | null;
      /**
       * Capture Mode
       * @default values
       * @enum {string}
       */
      capture_mode: "values" | "shapes";
      /** Name */
      name: string;
      /** Code */
      code: string;
      /**
       * Class Name
       * @default Attention
       */
      class_name: string;
      /** Constructor */
      constructor?: {
        [key: string]: unknown;
      };
      input?: components["schemas"]["InputSpec"];
      /** Id */
      id: string;
      /** Created At */
      created_at: string;
      /** Updated At */
      updated_at: string;
    };
    /** ProjectDraft */
    ProjectDraft: {
      blueprint?: components["schemas"]["Blueprint"] | null;
      /**
       * Capture Mode
       * @default values
       * @enum {string}
       */
      capture_mode: "values" | "shapes";
      /** Name */
      name: string;
      /** Code */
      code: string;
      /**
       * Class Name
       * @default Attention
       */
      class_name: string;
      /** Constructor */
      constructor?: {
        [key: string]: unknown;
      };
      input?: components["schemas"]["InputSpec"];
    };
    /** Run */
    Run: {
      /** Id */
      id: string;
      /** Project Id */
      project_id: string;
      /** Created At */
      created_at: string;
      project: components["schemas"]["ProjectDraft"];
      trace: components["schemas"]["Trace"];
    };
    /** RunError */
    RunError: {
      /** Type */
      type: string;
      /** Message */
      message: string;
      /** Line */
      line?: number | null;
    };
    /** RunSummary */
    RunSummary: {
      /** Id */
      id: string;
      /** Project Id */
      project_id: string;
      /** Created At */
      created_at: string;
      /** Operation Count */
      operation_count: number;
      /** Failed */
      failed: boolean;
    };
    /** SourceLocation */
    SourceLocation: {
      /** Line */
      line: number;
      /** Text */
      text: string;
    };
    /** Template */
    Template: {
      /** Id */
      id: string;
      /** Description */
      description: string;
      project: components["schemas"]["ProjectDraft"];
    };
    /** TensorState */
    TensorState: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Shape */
      shape: number[];
      /** Axes */
      axes: string[];
      /** Dtype */
      dtype: string;
      /** Strides */
      strides: number[];
      /** Storage Id */
      storage_id: string;
      /** Storage Offset */
      storage_offset: number;
      /** Contiguous */
      contiguous: boolean;
      /** Numel */
      numel: number;
      /** Values */
      values: (number | string)[];
      /**
       * Value Source
       * @default inline
       * @enum {string}
       */
      value_source: "inline" | "paged" | "shape";
      /** Minimum */
      minimum?: number | null;
      /** Maximum */
      maximum?: number | null;
      /**
       * Role
       * @default intermediate
       * @enum {string}
       */
      role: "input" | "parameter" | "intermediate";
    };
    /** Trace */
    Trace: {
      /**
       * Schema Version
       * @default 1
       * @constant
       */
      schema_version: "1";
      /** Operations */
      operations?: components["schemas"]["Operation"][];
      /** Tensors */
      tensors?: {
        [key: string]: components["schemas"]["TensorState"];
      };
      /** Input Ids */
      input_ids?: string[];
      /** Output Ids */
      output_ids?: string[];
      error?: components["schemas"]["RunError"] | null;
      /**
       * Stdout
       * @default
       */
      stdout: string;
      /**
       * Duration Ms
       * @default 0
       */
      duration_ms: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_v1_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  templates_api_v1_templates_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Template"][];
        };
      };
    };
  };
  toolbox_api_v1_toolbox_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  preview_composition_api_v1_compose_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompositionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CompositionPlan"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  projects_api_v1_projects_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"][];
        };
      };
    };
  };
  create_project_api_v1_projects_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectDraft"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_project_api_v1_projects__project_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_project_api_v1_projects__project_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectDraft"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_runs_api_v1_projects__project_id__runs_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunSummary"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  execute_api_v1_projects__project_id__runs_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Run"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_run_api_v1_runs__run_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Run"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  tensor_values_api_v1_runs__run_id__tensors__tensor_id__values_get: {
    parameters: {
      query: {
        indices: string;
      };
      header?: never;
      path: {
        run_id: string;
        tensor_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
