/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/sources/git": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Import Repository */
    post: operations["import_repository_api_v1_sources_git_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/environments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Python Environments */
    get: operations["python_environments_api_v1_environments_get"];
    put?: never;
    /** Setup Environment */
    post: operations["setup_environment_api_v1_environments_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/weights": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Weights */
    get: operations["list_weights_api_v1_weights_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/weights/upload": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload Weights */
    post: operations["upload_weights_api_v1_weights_upload_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/weights/check": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Check Weights */
    post: operations["check_weights_api_v1_weights_check_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_v1_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/templates": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Templates */
    get: operations["templates_api_v1_templates_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sources/read": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Read Source
     * @description A ready-to-run draft from code alone, exactly as the library uses.
     */
    post: operations["read_source_api_v1_sources_read_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/library": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Library */
    get: operations["library_api_v1_library_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/library/install": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Install Library
     * @description Create library projects that are not in the workspace yet, by name.
     */
    post: operations["install_library_api_v1_library_install_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/toolbox": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Toolbox */
    get: operations["toolbox_api_v1_toolbox_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/compose": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Preview Composition */
    post: operations["preview_composition_api_v1_compose_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/compose/check": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Check Composition */
    post: operations["check_composition_api_v1_compose_check_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/components": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Components */
    get: operations["components_api_v1_components_get"];
    put?: never;
    /** Save Component */
    post: operations["save_component_api_v1_components_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/input-fixtures": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Input Fixtures */
    get: operations["input_fixtures_api_v1_input_fixtures_get"];
    put?: never;
    /** Save Input Fixture */
    post: operations["save_input_fixture_api_v1_input_fixtures_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/input-fixtures/upload": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload Input */
    post: operations["upload_input_api_v1_input_fixtures_upload_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/projects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Projects */
    get: operations["projects_api_v1_projects_get"];
    put?: never;
    /** Create Project */
    post: operations["create_project_api_v1_projects_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/latest-runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Latest Runs */
    get: operations["latest_runs_api_v1_latest_runs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/projects/{project_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Project */
    get: operations["get_project_api_v1_projects__project_id__get"];
    /** Update Project */
    put: operations["update_project_api_v1_projects__project_id__put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/shape-check": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Shape Check
     * @description Dry-run a draft on metadata tensors. Nothing is saved and no values exist.
     */
    post: operations["shape_check_api_v1_shape_check_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/projects/{project_id}/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Runs */
    get: operations["list_runs_api_v1_projects__project_id__runs_get"];
    put?: never;
    /** Execute */
    post: operations["execute_api_v1_projects__project_id__runs_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{run_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Run */
    get: operations["get_run_api_v1_runs__run_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{run_id}/operations/{operation_id}/normalization": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Normalization Statistics */
    get: operations["normalization_statistics_api_v1_runs__run_id__operations__operation_id__normalization_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{run_id}/operations/{operation_id}/reduction": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Reduction Statistics */
    get: operations["reduction_statistics_api_v1_runs__run_id__operations__operation_id__reduction_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{run_id}/operations/{operation_id}/softmax": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Softmax Statistics */
    get: operations["softmax_statistics_api_v1_runs__run_id__operations__operation_id__softmax_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{run_id}/tensors/{tensor_id}/values": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Tensor Values */
    get: operations["tensor_values_api_v1_runs__run_id__tensors__tensor_id__values_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Blueprint */
    Blueprint: {
      /**
       * Has Input
       * @default false
       */
      has_input: boolean;
      /** Components */
      components?: components["schemas"]["ComponentSpec"][];
    };
    /** ComponentSpec */
    ComponentSpec: {
      /** Id */
      id: string;
      /** Kind */
      kind: string;
      /** Parameters */
      parameters?: {
        [key: string]: number;
      };
      custom?: components["schemas"]["CustomComponent"] | null;
      /** Arguments */
      arguments?: {
        [key: string]: unknown;
      } | null;
      /** Sources */
      sources?: string[] | null;
    };
    /** ComponentStage */
    ComponentStage: {
      /** Id */
      id: string;
      /** Title */
      title: string;
      /** Input Shape */
      input_shape: number[];
      /** Source Shapes */
      source_shapes?: number[][];
      /** Shape */
      shape?: number[] | null;
      /** Axes */
      axes?: string[];
      /** Error */
      error?: string | null;
    };
    /** CompositionPlan */
    CompositionPlan: {
      /**
       * Validation Required
       * @default false
       */
      validation_required: boolean;
      /** Code */
      code: string;
      /** Stages */
      stages: components["schemas"]["ComponentStage"][];
      /** Valid */
      valid: boolean;
      /** Error */
      error?: string | null;
    };
    /** CompositionRequest */
    CompositionRequest: {
      blueprint: components["schemas"]["Blueprint"];
      input?: components["schemas"]["InputSpec"];
      /**
       * Capture Mode
       * @default values
       * @enum {string}
       */
      capture_mode: "values" | "shapes";
    };
    /** CustomComponent */
    CustomComponent: {
      /** Name */
      name: string;
      /**
       * Description
       * @default
       */
      description: string;
      /** Code */
      code: string;
      /** Class Name */
      class_name: string;
      /** Constructor */
      constructor?: {
        [key: string]: unknown;
      };
      /** Id */
      id: string;
      /** Created At */
      created_at: string;
    };
    /** CustomComponentDraft */
    CustomComponentDraft: {
      /** Name */
      name: string;
      /**
       * Description
       * @default
       */
      description: string;
      /** Code */
      code: string;
      /** Class Name */
      class_name: string;
      /** Constructor */
      constructor?: {
        [key: string]: unknown;
      };
    };
    /** EnvironmentRequest */
    EnvironmentRequest: {
      /** Requirements */
      requirements?: string[];
    };
    /** ForwardInput */
    ForwardInput: {
      /** Name */
      name: string;
      /**
       * Binding
       * @default positional
       * @enum {string}
       */
      binding: "positional" | "keyword";
      input: components["schemas"]["InputSpec"];
    };
    /** GitImportRequest */
    GitImportRequest: {
      /** Repository */
      repository: string;
      /**
       * Revision
       * @default HEAD
       */
      revision: string;
      /**
       * Subdirectory
       * @default .
       */
      subdirectory: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * Histogram
     * @description How a tensor's finite values are spread, in equal-width bins.
     */
    Histogram: {
      /** Low */
      low: number;
      /** High */
      high: number;
      /** Counts */
      counts: number[];
      /** Zeros */
      zeros: number;
      /** Non Finite */
      non_finite: number;
      /** Mean */
      mean?: number | null;
      /** Std */
      std?: number | null;
    };
    /** InputFixture */
    InputFixture: {
      /** Name */
      name: string;
      input: components["schemas"]["InputSpec"];
      /**
       * Capture Mode
       * @default values
       * @enum {string}
       */
      capture_mode: "values" | "shapes";
      /** Id */
      id: string;
      /** Created At */
      created_at: string;
    };
    /** InputFixtureDraft */
    InputFixtureDraft: {
      /** Name */
      name: string;
      input: components["schemas"]["InputSpec"];
      /**
       * Capture Mode
       * @default values
       * @enum {string}
       */
      capture_mode: "values" | "shapes";
    };
    /** InputSpec */
    InputSpec: {
      /** Shape */
      shape?: number[];
      /**
       * Generator
       * @default arange
       * @enum {string}
       */
      generator:
        "arange" | "random" | "ones" | "zeros" | "uploaded" | "image" | "text";
      uploaded?: components["schemas"]["UploadedTensor"] | null;
      /** Text */
      text?: string | null;
      /**
       * Dtype
       * @default float32
       * @enum {string}
       */
      dtype: "float32" | "float64" | "int64";
      /**
       * Seed
       * @default 7
       */
      seed: number;
      /**
       * Random Stream
       * @default model
       * @enum {string}
       */
      random_stream: "model" | "input";
      /** Axis Names */
      axis_names?: string[];
    };
    /**
     * LatestRun
     * @description A project's newest run, for marking projects in lists.
     */
    LatestRun: {
      /** Project Id */
      project_id: string;
      /** Run Id */
      run_id: string;
      /** Created At */
      created_at: string;
      /** Operation Count */
      operation_count: number;
      /** Failed */
      failed: boolean;
    };
    /** LayerNormalizationStatistics */
    LayerNormalizationStatistics: {
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "non_finite" | "overflow";
      /** Mean */
      mean?: number | null;
      /** Variance */
      variance?: number | null;
      /** Denominator */
      denominator?: number | null;
      /** Operation Id */
      operation_id: string;
      /** Tensor Id */
      tensor_id: string;
      /** Group */
      group: number;
      /** Start */
      start: number;
      /** Count */
      count: number;
    };
    /** Lesson */
    Lesson: {
      /** Title */
      title: string;
      /** Summary */
      summary: string;
      /** Detail */
      detail: string;
      /**
       * Category
       * @enum {string}
       */
      category:
        "layout" | "compute" | "normalize" | "memory" | "creation" | "generic";
      /**
       * Interaction
       * @default inspect
       * @enum {string}
       */
      interaction:
        | "mapping"
        | "dot_product"
        | "normalization"
        | "patch_projection"
        | "linear_projection"
        | "broadcast_add"
        | "tensor_assembly"
        | "convolution"
        | "pooling"
        | "layer_normalization"
        | "relation"
        | "activation"
        | "reduction"
        | "inspect";
      /** Relation */
      relation?: {
        [key: string]: unknown;
      } | null;
      /** Patch Size */
      patch_size?: number[] | null;
      /** Mapping */
      mapping?: number[] | null;
      /** Axis Order */
      axis_order?: number[] | null;
      /** Mapping Rule */
      mapping_rule?: ("identity" | "permutation" | "unfold" | "roll") | null;
    };
    /** LibraryEntry */
    LibraryEntry: {
      /** Id */
      id: string;
      /** Number */
      number: number;
      /** Title */
      title: string;
      /** Summary */
      summary: string;
      /** Track */
      track: string;
      /** Code */
      code: string;
    };
    /**
     * LoopStep
     * @description One enclosing loop of an operation and the iteration it ran in.
     */
    LoopStep: {
      /** Id */
      id: string;
      /** Line */
      line: number;
      /** File */
      file?: string | null;
      /** Text */
      text: string;
      /** Iteration */
      iteration: number;
    };
    /** ModuleCall */
    ModuleCall: {
      /** Id */
      id: string;
      /** Parent Id */
      parent_id?: string | null;
      /** Path */
      path: string;
      /** Module Type */
      module_type: string;
      /** Start Index */
      start_index: number;
      /** End Index */
      end_index: number;
      /** Inputs */
      inputs?: string[];
      /** Outputs */
      outputs?: string[];
    };
    /** Operation */
    Operation: {
      /** Id */
      id: string;
      /** Index */
      index: number;
      /** Kind */
      kind: string;
      /** Function */
      function: string;
      /** Inputs */
      inputs: string[];
      /** Outputs */
      outputs: string[];
      /** Mutations */
      mutations?: components["schemas"]["TensorMutation"][];
      /** Arguments */
      arguments: {
        [key: string]: unknown;
      };
      source: components["schemas"]["SourceLocation"] | null;
      /** Module */
      module: string;
      lesson: components["schemas"]["Lesson"];
      /**
       * Status
       * @default ok
       * @enum {string}
       */
      status: "ok" | "error";
      /** Error */
      error?: string | null;
      /** Loops */
      loops?: components["schemas"]["LoopStep"][];
    };
    /** Project */
    Project: {
      blueprint?: components["schemas"]["Blueprint"] | null;
      /** Script */
      script?: string | null;
      /**
       * Capture Mode
       * @default values
       * @enum {string}
       */
      capture_mode: "values" | "shapes";
      /** Name */
      name: string;
      /** Code */
      code: string;
      /**
       * Class Name
       * @default Attention
       */
      class_name: string;
      /** Constructor */
      constructor?: {
        [key: string]: unknown;
      };
      input?: components["schemas"]["InputSpec"];
      /**
       * Input Name
       * @default x
       */
      input_name: string;
      /**
       * Input Binding
       * @default positional
       * @enum {string}
       */
      input_binding: "positional" | "keyword";
      /** Additional Inputs */
      additional_inputs?: components["schemas"]["ForwardInput"][];
      weights?: components["schemas"]["SavedWeights"] | null;
      /** Files */
      files?: {
        [key: string]: string;
      };
      /**
       * Entry Path
       * @default model.py
       */
      entry_path: string;
      /**
       * Import Root
       * @default .
       */
      import_root: string;
      /** Repository */
      repository?: {
        [key: string]: string;
      } | null;
      /** Environment */
      environment?: string | null;
      /** Id */
      id: string;
      /** Created At */
      created_at: string;
      /** Updated At */
      updated_at: string;
    };
    /** ProjectDraft */
    ProjectDraft: {
      blueprint?: components["schemas"]["Blueprint"] | null;
      /** Script */
      script?: string | null;
      /**
       * Capture Mode
       * @default values
       * @enum {string}
       */
      capture_mode: "values" | "shapes";
      /** Name */
      name: string;
      /** Code */
      code: string;
      /**
       * Class Name
       * @default Attention
       */
      class_name: string;
      /** Constructor */
      constructor?: {
        [key: string]: unknown;
      };
      input?: components["schemas"]["InputSpec"];
      /**
       * Input Name
       * @default x
       */
      input_name: string;
      /**
       * Input Binding
       * @default positional
       * @enum {string}
       */
      input_binding: "positional" | "keyword";
      /** Additional Inputs */
      additional_inputs?: components["schemas"]["ForwardInput"][];
      weights?: components["schemas"]["SavedWeights"] | null;
      /** Files */
      files?: {
        [key: string]: string;
      };
      /**
       * Entry Path
       * @default model.py
       */
      entry_path: string;
      /**
       * Import Root
       * @default .
       */
      import_root: string;
      /** Repository */
      repository?: {
        [key: string]: string;
      } | null;
      /** Environment */
      environment?: string | null;
    };
    /**
     * ReadProject
     * @description A ready-to-run draft and anything the reader could not use.
     */
    ReadProject: {
      draft: components["schemas"]["ProjectDraft"];
      /** Title */
      title: string;
      /** Summary */
      summary: string;
      /** Notes */
      notes: string[];
    };
    /** ReductionStatistics */
    ReductionStatistics: {
      /** Run Id */
      run_id: string;
      /** Operation Id */
      operation_id: string;
      /** Tensor Id */
      tensor_id: string;
      /** Output Index */
      output_index: number;
      /** Count */
      count: number;
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "non_finite" | "overflow";
      /** Sum */
      sum?: number | string | null;
      /** Result */
      result?: number | string | null;
    };
    /** Run */
    Run: {
      /** Id */
      id: string;
      /** Project Id */
      project_id: string;
      /** Created At */
      created_at: string;
      project: components["schemas"]["ProjectDraft"];
      trace: components["schemas"]["Trace"];
    };
    /** RunError */
    RunError: {
      /** Type */
      type: string;
      /** Message */
      message: string;
      /** Line */
      line?: number | null;
      /** File */
      file?: string | null;
    };
    /** RunSummary */
    RunSummary: {
      /** Id */
      id: string;
      /** Project Id */
      project_id: string;
      /** Created At */
      created_at: string;
      /** Operation Count */
      operation_count: number;
      /** Failed */
      failed: boolean;
      project?: components["schemas"]["ProjectDraft"] | null;
    };
    /** RuntimeEnvironment */
    RuntimeEnvironment: {
      /** Id */
      id: string;
      /** Requirements */
      requirements: string[];
      /** Python */
      python: string;
      /** Packages */
      packages: {
        [key: string]: string;
      };
    };
    /** SavedWeights */
    SavedWeights: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** File Name */
      file_name: string;
      /** Created At */
      created_at: string;
      /** Sha256 */
      sha256: string;
      /** Byte Count */
      byte_count: number;
      /** Tensors */
      tensors: components["schemas"]["WeightTensor"][];
    };
    /** ShapeCheck */
    ShapeCheck: {
      project: components["schemas"]["ProjectDraft"];
      trace: components["schemas"]["Trace"];
    };
    /** SoftmaxStatistics */
    SoftmaxStatistics: {
      /** Run Id */
      run_id: string;
      /** Operation Id */
      operation_id: string;
      /** Tensor Id */
      tensor_id: string;
      /** Group */
      group: number;
      /** Count */
      count: number;
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "non_finite" | "all_masked";
      /** Maximum */
      maximum?: number | null;
      /** Denominator */
      denominator?: number | null;
      /** Masked Count */
      masked_count?: number | null;
    };
    /** SourceImport */
    SourceImport: {
      /** Files */
      files: {
        [key: string]: string;
      };
      /** Repository */
      repository: {
        [key: string]: string;
      };
      /** Skipped */
      skipped: number;
    };
    /** SourceLocation */
    SourceLocation: {
      /** Line */
      line: number;
      /** Text */
      text: string;
      /** File */
      file?: string | null;
    };
    /** SourceRead */
    SourceRead: {
      /** Code */
      code: string;
      /** Name */
      name?: string | null;
      /** Model */
      model?: string | null;
    };
    /** Template */
    Template: {
      /** Id */
      id: string;
      /** Description */
      description: string;
      project: components["schemas"]["ProjectDraft"];
    };
    /** TensorMutation */
    TensorMutation: {
      /** Before */
      before: string;
      /** After */
      after: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: "write" | "alias" | "metadata";
    };
    /** TensorState */
    TensorState: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Shape */
      shape: number[];
      /** Axes */
      axes: string[];
      /** Dtype */
      dtype: string;
      /** Strides */
      strides: number[];
      /** Storage Id */
      storage_id: string;
      /** Storage Offset */
      storage_offset: number;
      /** Contiguous */
      contiguous: boolean;
      /** Numel */
      numel: number;
      /** Values */
      values: (number | string)[];
      /**
       * Value Source
       * @default inline
       * @enum {string}
       */
      value_source: "inline" | "paged" | "shape";
      /** Minimum */
      minimum?: number | null;
      /** Maximum */
      maximum?: number | null;
      histogram?: components["schemas"]["Histogram"] | null;
      /**
       * Role
       * @default intermediate
       * @enum {string}
       */
      role: "input" | "parameter" | "intermediate";
    };
    /** Trace */
    Trace: {
      /**
       * Schema Version
       * @default 1
       * @constant
       */
      schema_version: "1";
      /** Runtime */
      runtime?: {
        [key: string]: string;
      };
      /** Operations */
      operations?: components["schemas"]["Operation"][];
      /** Module Calls */
      module_calls?: components["schemas"]["ModuleCall"][];
      /** Tensors */
      tensors?: {
        [key: string]: components["schemas"]["TensorState"];
      };
      /** Input Ids */
      input_ids?: string[];
      /** Output Ids */
      output_ids?: string[];
      error?: components["schemas"]["RunError"] | null;
      /**
       * Stdout
       * @default
       */
      stdout: string;
      /** Warnings */
      warnings?: string[];
      /**
       * Duration Ms
       * @default 0
       */
      duration_ms: number;
      weight_check?: components["schemas"]["WeightCheck"] | null;
    };
    /** UploadedTensor */
    UploadedTensor: {
      /** Id */
      id: string;
      /** File Name */
      file_name: string;
      /** Sha256 */
      sha256: string;
      /** Shape */
      shape: number[];
      /**
       * Dtype
       * @enum {string}
       */
      dtype: "float32" | "float64" | "int64";
      /** Byte Count */
      byte_count: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** WeightCheck */
    WeightCheck: {
      /** Compatible */
      compatible: boolean;
      /** Issues */
      issues?: string[];
      /**
       * Tensor Count
       * @default 0
       */
      tensor_count: number;
    };
    /** WeightTensor */
    WeightTensor: {
      /** Name */
      name: string;
      /** Shape */
      shape: number[];
      /** Dtype */
      dtype: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  import_repository_api_v1_sources_git_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GitImportRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceImport"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  python_environments_api_v1_environments_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RuntimeEnvironment"][];
        };
      };
    };
  };
  setup_environment_api_v1_environments_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EnvironmentRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RuntimeEnvironment"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_weights_api_v1_weights_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SavedWeights"][];
        };
      };
    };
  };
  upload_weights_api_v1_weights_upload_post: {
    parameters: {
      query: {
        name: string;
        file_name: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/octet-stream": string;
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SavedWeights"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  check_weights_api_v1_weights_check_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectDraft"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WeightCheck"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_api_v1_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  templates_api_v1_templates_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Template"][];
        };
      };
    };
  };
  read_source_api_v1_sources_read_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SourceRead"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadProject"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  library_api_v1_library_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LibraryEntry"][];
        };
      };
    };
  };
  install_library_api_v1_library_install_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"][];
        };
      };
    };
  };
  toolbox_api_v1_toolbox_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  preview_composition_api_v1_compose_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompositionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CompositionPlan"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  check_composition_api_v1_compose_check_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompositionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CompositionPlan"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  components_api_v1_components_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomComponent"][];
        };
      };
    };
  };
  save_component_api_v1_components_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CustomComponentDraft"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomComponent"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  input_fixtures_api_v1_input_fixtures_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InputFixture"][];
        };
      };
    };
  };
  save_input_fixture_api_v1_input_fixtures_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InputFixtureDraft"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InputFixture"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  upload_input_api_v1_input_fixtures_upload_post: {
    parameters: {
      query: {
        name: string;
        file_name: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/octet-stream": string;
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InputFixture"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  projects_api_v1_projects_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"][];
        };
      };
    };
  };
  create_project_api_v1_projects_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectDraft"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  latest_runs_api_v1_latest_runs_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LatestRun"][];
        };
      };
    };
  };
  get_project_api_v1_projects__project_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_project_api_v1_projects__project_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectDraft"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  shape_check_api_v1_shape_check_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectDraft"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ShapeCheck"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_runs_api_v1_projects__project_id__runs_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunSummary"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  execute_api_v1_projects__project_id__runs_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Run"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_run_api_v1_runs__run_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Run"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  normalization_statistics_api_v1_runs__run_id__operations__operation_id__normalization_get: {
    parameters: {
      query: {
        group: number;
      };
      header?: never;
      path: {
        run_id: string;
        operation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LayerNormalizationStatistics"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reduction_statistics_api_v1_runs__run_id__operations__operation_id__reduction_get: {
    parameters: {
      query: {
        output_index: number;
      };
      header?: never;
      path: {
        run_id: string;
        operation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReductionStatistics"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  softmax_statistics_api_v1_runs__run_id__operations__operation_id__softmax_get: {
    parameters: {
      query: {
        group: number;
      };
      header?: never;
      path: {
        run_id: string;
        operation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SoftmaxStatistics"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  tensor_values_api_v1_runs__run_id__tensors__tensor_id__values_get: {
    parameters: {
      query: {
        indices: string;
      };
      header?: never;
      path: {
        run_id: string;
        tensor_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
